version: "3.9"
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  api:
    build:
      context: ./api
    environment:
      - MONGO_URL=${MONGO_URL:-mongodb://mongo:27017/word-detective-lite}
      - DAILY_SEED_SALT=${DAILY_SEED_SALT:-change-me}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:5173}
      - MODEL_NAME=${MODEL_NAME:-sentence-transformers/all-MiniLM-L6-v2}
    depends_on:
      - mongo
    ports:
      - "8000:8000"
  web:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./web:/app
    command: sh -c "npm ci && npm run dev -- --host"
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=${VITE_API_BASE:-http://localhost:8000}
    depends_on:
      - api
volumes:
  mongo_data:
